name: Go Build and Deploy

on:
  push:
    branches:
      - main  # برای هر push به branch main اجرا می‌شود
  pull_request:
    branches:
      - main  # برای هر pull request به branch main اجرا می‌شود

jobs:
  build:
    runs-on: ubuntu-latest  # این job روی Ubuntu اجرا می‌شود

    steps:
      # Step 1: Checkout the code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # یا نسخه مورد نظر Go

      # Step 3: Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 5: Build the Go executable
      - name: Build executable
        run: go build -o phpvm

      # Step 6: Upload the built executable as an artifact (برای دانلود)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: phpvm-executable
          path: phpvm
          
      # Optional: You can deploy or run other steps here
