name: Build PHPVM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build PHPVM
        run: |
          set -ex
          go build -o phpvm

      - name: Upload PHPVM binary
        uses: actions/upload-artifact@v4
        with:
          name: phpvm
          path: phpvm
